{% set name = "focal-stats" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/focal_stats-{{ version }}.tar.gz
  sha256: 8a954104fe39a81aa8709de91515ad6a7872b5cb8615efa4381318722801f558

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - focal_stats
    - focal_stats.core.focal_correlation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/focal-stats/
  license: MIT
  license_file: LICENSE
  summary: Focal statistics for Python
  doc_url: https://focal-stats.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/focal-stats

extra:
  recipe-maintainers:
    - jasperroebroek
