{% set name = "focal-stats" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/focal_stats-{{ version }}.tar.gz
  sha256: 60456f83e6d376d46e1e4bfafef587c7d71f26d613b2c1ddaec7b6ac358efc5b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - focal_stats
    - focal_stats.core.focal_correlation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/focal-stats/
  license: MIT
  license_file: LICENSE
  summary: Focal statistics for Python
  doc_url: https://focal-stats.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/focal-stats

extra:
  recipe-maintainers:
    - jasperroebroek
